### ISSUE TITLE
no output files in the filtered_structures folder

### ISSUE THREAD

**Issue by aaaaaaaaa21-code** [ikalvet/heme_binder_diffusion#10]
Hello,

When I run the Analyzing diffusion outputs module, the diffusion_analysis.sc file is generated correctly. However, there are no output files in the filtered_structures folder. Does this mean that no good structures were filtered out? But I am just using 7o2g as an example.

Thank you!

**Comment by ikalvet** [comment]
Hi! There is indeed a solid chance that none of the diffusion outputs ended up satisfying the filtering criteria. The "diffusion_analysis.sc" file contents can give you an idea where most designs might be failing. Also if you run the analysis with "--analyze" flag, then the script will not perform any filtering for you and can give a better understanding of the distribution of metrics (i.e. all scaffolds are scored for all metrics).

**Comment by aaaaaaaaa21-code** [comment]
> Hi! There is indeed a solid chance that none of the diffusion outputs ended up satisfying the filtering criteria. The "diffusion_analysis.sc" file contents can give you an idea where most designs might be failing. Also if you run the analysis with "--analyze" flag, then the script will not perform any filtering for you and can give a better understanding of the distribution of metrics (i.e. all scaffolds are scored for all metrics).

Thank you for your answer, I have solved the problem!
