### ISSUE TITLE
A super little bug

### ISSUE THREAD

**Issue by cn-lugen** [ikalvet/heme_binder_diffusion#5]
"Thank you for uploading pssm_tools.py. Additionally, when I ran pipeline.ipynb, I found that line 39 of align_add_ligand_relax.py also needs modification."

**Comment by ikalvet** [comment]
Thank you for finding this! I fixed that and found a few other similar issues in two other files (`scripts/design/heme_pocket_ligMPNN.py` and `scripts/design/scoring/heme_scoring.py`). The reason for all of that mess was that I originally intended to upload this pipeline as a subdirectory in https://github.com/ikalvet/heme_binder_design, but later decided it deserves its own repo.
